"""add lockout fields

Revision ID: 8682468c29c9
Revises: 
Create Date: 2026-09-25 15:39:18.322651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8682468c29c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commandes auto générées par Alembic - veuillez ajuster ! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        # 1. Ajouter d'abord les colonnes en nullable
        batch_op.add_column(sa.Column('failed_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
    
    # 2. Remplir les lignes existantes avec une valeur par défaut
    op.execute("UPDATE admins SET failed_attempts = 0 WHERE failed_attempts IS NULL")
    
    # 3. Maintenant rendre la colonne NOT NULL
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('failed_attempts', nullable=False)
    # ### fin des commandes Alembic ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_attempts')

    # ### end Alembic commands ###
